---
- name: "Deploy E-Commerce website"
  hosts: "{{ host }}"
  become: yes
  become_user: root
  tasks:
    - name: "Install firewall daemon"
      package:
        name: firewalld
        state: present

    - name: "Start firewall service"
      service:
        name: firewalld
        enabled: yes
        state: started

    - name: "Install MariaDB server"
      package:
        name: mariadb-server
        state: present

    - name: "Start MariaDB service"
      service:
        name: mariadb
        enabled: yes
        state: started

    - name: "Permit traffic on default port for MariaDB through firewall"
      firewalld:
        port: 3306/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: "Install PyMySQL"
      pip:
        name: PyMySQL

    - name: "Create ecomdb database"
      mysql_db:
        name: ecomdb
        config_file: /etc/my.cnf
        login_unix_socket: /var/lib/mysql/mysql.sock
        state: present

    - name: "Create a user for the database ecomdb"
      no_log: yes
      mysql_user:
        name: ecomuser
        password: ecompassword
        priv: "*.*:ALL"
        state: present

    - name: "Install httpd, php and php-mysql daemon"
      package:
        name: ['httpd', 'php', 'php-mysql']
        state: installed

    - name: "Permit traffic on default port for httpd through firewall"
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: "Ensure httpd.conf file points to index.php"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^(.*)index.html(.*)$'
        line: "    DirectoryIndex index.php"
        backrefs: yes

    - name: "Start httpd service"
      service:
        name: httpd
        enabled: true
        state: started

    - name: "Download Git repo"
      git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html/
        version: master
        force: yes

    - name: "Run SQL queries against a database"
      mysql_db:
        name: ecomdb
        state: import
        target: /var/www/html/assets/db-load-script.sql
      ignore_errors: yes

    - name: "Modify database connection host"
      lineinfile:
        path: /var/www/html/index.php
        regexp: '^(.*)ecomuser(.*)$'
        line: "                        $link = mysqli_connect('localhost', 'ecomuser', 'ecompassword', 'ecomdb');"
        backrefs: yes

    - name: "Test httpd webhost"
      get_url:
        url: http://localhost
        dest: ~/get_url_output.txt
        mode: '644'
      register: webhost_output

    - name: "Print return code"
      debug:
        msg: "{{ webhost_output.status_code }}"